# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401
import sys  # noqa: F401

# python 2 and python 3 compatibility library
import six

from keycloak_admin_client.api_client import ApiClient
from keycloak_admin_client.exceptions import (
    ApiTypeError,
    ApiValueError
)
from keycloak_admin_client.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    int,
    none_type,
    str,
    validate_and_convert_types
)
from keycloak_admin_client.models import identity_provider_representation
from keycloak_admin_client.models import management_permission_reference
from keycloak_admin_client.models import identity_provider_mapper_type_representation
from keycloak_admin_client.models import identity_provider_mapper_representation


class IdentityProvidersApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __admin_realms_realm_identity_provider_import_config_post(
            self,
            realm,
            **kwargs
        ):
            """Import identity provider from JSON body  # noqa: E501

            Import identity provider from uploaded JSON file  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_import_config_post(realm, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):

            Keyword Args:
                request_body ({str: (str,)}): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                {str: (str,)}
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_import_config_post = Endpoint(
            settings={
                'response_type': ({str: (str,)},),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/import-config',
                'operation_id': 'admin_realms_realm_identity_provider_import_config_post',
                'http_method': 'POST',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'request_body',
                ],
                'required': [
                    'realm',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'request_body':
                        ({str: (str,)},),
                },
                'attribute_map': {
                    'realm': 'realm',
                },
                'location_map': {
                    'realm': 'path',
                    'request_body': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_import_config_post
        )

        def __admin_realms_realm_identity_provider_instances_alias_delete(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Delete the identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_delete(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_delete = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_delete',
                'http_method': 'DELETE',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_delete
        )

        def __admin_realms_realm_identity_provider_instances_alias_export_get(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Export public broker configuration for identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_export_get(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                format (str): Format to use. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_export_get = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/export',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_export_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                    'format',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                    'format':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                    'format': 'format',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                    'format': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_export_get
        )

        def __admin_realms_realm_identity_provider_instances_alias_get(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Get the identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_get(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                identity_provider_representation.IdentityProviderRepresentation
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_get = Endpoint(
            settings={
                'response_type': (identity_provider_representation.IdentityProviderRepresentation,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_get
        )

        def __admin_realms_realm_identity_provider_instances_alias_management_permissions_get(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Return object stating whether client Authorization permissions have been initialized or not and a reference  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_management_permissions_get(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                management_permission_reference.ManagementPermissionReference
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_management_permissions_get = Endpoint(
            settings={
                'response_type': (management_permission_reference.ManagementPermissionReference,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/management/permissions',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_management_permissions_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_management_permissions_get
        )

        def __admin_realms_realm_identity_provider_instances_alias_management_permissions_put(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Return object stating whether client Authorization permissions have been initialized or not and a reference  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_management_permissions_put(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                management_permission_reference_management_permission_reference (management_permission_reference.ManagementPermissionReference): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                management_permission_reference.ManagementPermissionReference
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_management_permissions_put = Endpoint(
            settings={
                'response_type': (management_permission_reference.ManagementPermissionReference,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/management/permissions',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_management_permissions_put',
                'http_method': 'PUT',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                    'management_permission_reference_management_permission_reference',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                    'management_permission_reference_management_permission_reference':
                        (management_permission_reference.ManagementPermissionReference,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                    'management_permission_reference_management_permission_reference': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_management_permissions_put
        )

        def __admin_realms_realm_identity_provider_instances_alias_mapper_types_get(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Get mapper types for identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_mapper_types_get(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                {str: (identity_provider_mapper_type_representation.IdentityProviderMapperTypeRepresentation,)}
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_mapper_types_get = Endpoint(
            settings={
                'response_type': ({str: (identity_provider_mapper_type_representation.IdentityProviderMapperTypeRepresentation,)},),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/mapper-types',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_mapper_types_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    '*/*'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_mapper_types_get
        )

        def __admin_realms_realm_identity_provider_instances_alias_mappers_get(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Get mappers for identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_mappers_get(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                [identity_provider_mapper_representation.IdentityProviderMapperRepresentation]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_mappers_get = Endpoint(
            settings={
                'response_type': ([identity_provider_mapper_representation.IdentityProviderMapperRepresentation],),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/mappers',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_mappers_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_mappers_get
        )

        def __admin_realms_realm_identity_provider_instances_alias_mappers_id_delete(
            self,
            id,
            realm,
            alias,
            **kwargs
        ):
            """Delete a mapper for the identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_mappers_id_delete(id, realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                id (str): Mapper id
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['id'] = \
                id
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_mappers_id_delete = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/mappers/{id}',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_mappers_id_delete',
                'http_method': 'DELETE',
                'servers': [],
            },
            params_map={
                'all': [
                    'id',
                    'realm',
                    'alias',
                ],
                'required': [
                    'id',
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'id': 'id',
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'id': 'path',
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_mappers_id_delete
        )

        def __admin_realms_realm_identity_provider_instances_alias_mappers_id_get(
            self,
            id,
            realm,
            alias,
            **kwargs
        ):
            """Get mapper by id for the identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_mappers_id_get(id, realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                id (str):
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                identity_provider_mapper_representation.IdentityProviderMapperRepresentation
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['id'] = \
                id
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_mappers_id_get = Endpoint(
            settings={
                'response_type': (identity_provider_mapper_representation.IdentityProviderMapperRepresentation,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/mappers/{id}',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_mappers_id_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'id',
                    'realm',
                    'alias',
                ],
                'required': [
                    'id',
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'id': 'id',
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'id': 'path',
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_mappers_id_get
        )

        def __admin_realms_realm_identity_provider_instances_alias_mappers_id_put(
            self,
            id,
            realm,
            alias,
            **kwargs
        ):
            """Update a mapper for the identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_mappers_id_put(id, realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                id (str): Mapper id
                realm (str):
                alias (str):

            Keyword Args:
                identity_provider_mapper_representation_identity_provider_mapper_representation (identity_provider_mapper_representation.IdentityProviderMapperRepresentation): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['id'] = \
                id
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_mappers_id_put = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/mappers/{id}',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_mappers_id_put',
                'http_method': 'PUT',
                'servers': [],
            },
            params_map={
                'all': [
                    'id',
                    'realm',
                    'alias',
                    'identity_provider_mapper_representation_identity_provider_mapper_representation',
                ],
                'required': [
                    'id',
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'id':
                        (str,),
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                    'identity_provider_mapper_representation_identity_provider_mapper_representation':
                        (identity_provider_mapper_representation.IdentityProviderMapperRepresentation,),
                },
                'attribute_map': {
                    'id': 'id',
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'id': 'path',
                    'realm': 'path',
                    'alias': 'path',
                    'identity_provider_mapper_representation_identity_provider_mapper_representation': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_mappers_id_put
        )

        def __admin_realms_realm_identity_provider_instances_alias_mappers_post(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Add a mapper to identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_mappers_post(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                identity_provider_mapper_representation_identity_provider_mapper_representation (identity_provider_mapper_representation.IdentityProviderMapperRepresentation): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_mappers_post = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/mappers',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_mappers_post',
                'http_method': 'POST',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                    'identity_provider_mapper_representation_identity_provider_mapper_representation',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                    'identity_provider_mapper_representation_identity_provider_mapper_representation':
                        (identity_provider_mapper_representation.IdentityProviderMapperRepresentation,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                    'identity_provider_mapper_representation_identity_provider_mapper_representation': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_mappers_post
        )

        def __admin_realms_realm_identity_provider_instances_alias_put(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Update the identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_put(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                identity_provider_representation_identity_provider_representation (identity_provider_representation.IdentityProviderRepresentation): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_put = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_put',
                'http_method': 'PUT',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                    'identity_provider_representation_identity_provider_representation',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                    'identity_provider_representation_identity_provider_representation':
                        (identity_provider_representation.IdentityProviderRepresentation,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                    'identity_provider_representation_identity_provider_representation': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_put
        )

        def __admin_realms_realm_identity_provider_instances_alias_reload_keys_get(
            self,
            realm,
            alias,
            **kwargs
        ):
            """Reaload keys for the identity provider if the provider supports it, \"true\" is returned if reload was performed, \"false\" if not.  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_alias_reload_keys_get(realm, alias, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):
                alias (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            kwargs['alias'] = \
                alias
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_alias_reload_keys_get = Endpoint(
            settings={
                'response_type': (bool,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances/{alias}/reload-keys',
                'operation_id': 'admin_realms_realm_identity_provider_instances_alias_reload_keys_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'alias',
                ],
                'required': [
                    'realm',
                    'alias',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'alias':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'alias': 'alias',
                },
                'location_map': {
                    'realm': 'path',
                    'alias': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_alias_reload_keys_get
        )

        def __admin_realms_realm_identity_provider_instances_get(
            self,
            realm,
            **kwargs
        ):
            """List identity providers  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_get(realm, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):

            Keyword Args:
                brief_representation (bool): Boolean which defines whether brief representations are returned (default: false). [optional]
                first (int): Pagination offset. [optional]
                max (int): Maximum results size (defaults to 100). [optional]
                realm_only (bool): Boolean which defines if only realm-level IDPs (not associated with orgs) should be returned (default: false). [optional]
                search (str): Filter specific providers by name. Search can be prefix (name*), contains (*name*) or exact (\&quot;name\&quot;). Default prefixed.. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                [identity_provider_representation.IdentityProviderRepresentation]
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_get = Endpoint(
            settings={
                'response_type': ([identity_provider_representation.IdentityProviderRepresentation],),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances',
                'operation_id': 'admin_realms_realm_identity_provider_instances_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'brief_representation',
                    'first',
                    'max',
                    'realm_only',
                    'search',
                ],
                'required': [
                    'realm',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'brief_representation':
                        (bool,),
                    'first':
                        (int,),
                    'max':
                        (int,),
                    'realm_only':
                        (bool,),
                    'search':
                        (str,),
                },
                'attribute_map': {
                    'realm': 'realm',
                    'brief_representation': 'briefRepresentation',
                    'first': 'first',
                    'max': 'max',
                    'realm_only': 'realmOnly',
                    'search': 'search',
                },
                'location_map': {
                    'realm': 'path',
                    'brief_representation': 'query',
                    'first': 'query',
                    'max': 'query',
                    'realm_only': 'query',
                    'search': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_get
        )

        def __admin_realms_realm_identity_provider_instances_post(
            self,
            realm,
            **kwargs
        ):
            """Create a new identity provider  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_instances_post(realm, async_req=True)
            >>> result = thread.get()

            Args:
                realm (str):

            Keyword Args:
                identity_provider_representation_identity_provider_representation (identity_provider_representation.IdentityProviderRepresentation): [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['realm'] = \
                realm
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_instances_post = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/instances',
                'operation_id': 'admin_realms_realm_identity_provider_instances_post',
                'http_method': 'POST',
                'servers': [],
            },
            params_map={
                'all': [
                    'realm',
                    'identity_provider_representation_identity_provider_representation',
                ],
                'required': [
                    'realm',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'realm':
                        (str,),
                    'identity_provider_representation_identity_provider_representation':
                        (identity_provider_representation.IdentityProviderRepresentation,),
                },
                'attribute_map': {
                    'realm': 'realm',
                },
                'location_map': {
                    'realm': 'path',
                    'identity_provider_representation_identity_provider_representation': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_instances_post
        )

        def __admin_realms_realm_identity_provider_providers_provider_id_get(
            self,
            provider_id,
            realm,
            **kwargs
        ):
            """Get the identity provider factory for that provider id  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True
            >>> thread = api.admin_realms_realm_identity_provider_providers_provider_id_get(provider_id, realm, async_req=True)
            >>> result = thread.get()

            Args:
                provider_id (str): The provider id to get the factory
                realm (str):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int): specifies the index of the server
                    that we want to use.
                    Default is 0.
                async_req (bool): execute request asynchronously

            Returns:
                bool, date, datetime, dict, float, int, list, str
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index', 0)
            kwargs['provider_id'] = \
                provider_id
            kwargs['realm'] = \
                realm
            return self.call_with_http_info(**kwargs)

        self.admin_realms_realm_identity_provider_providers_provider_id_get = Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str,),
                'auth': [],
                'endpoint_path': '/admin/realms/{realm}/identity-provider/providers/{provider_id}',
                'operation_id': 'admin_realms_realm_identity_provider_providers_provider_id_get',
                'http_method': 'GET',
                'servers': [],
            },
            params_map={
                'all': [
                    'provider_id',
                    'realm',
                ],
                'required': [
                    'provider_id',
                    'realm',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'provider_id':
                        (str,),
                    'realm':
                        (str,),
                },
                'attribute_map': {
                    'provider_id': 'provider_id',
                    'realm': 'realm',
                },
                'location_map': {
                    'provider_id': 'path',
                    'realm': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__admin_realms_realm_identity_provider_providers_provider_id_get
        )


class Endpoint(object):
    def __init__(self, settings=None, params_map=None, root_map=None,
                 headers_map=None, api_client=None, callable=None):
        """Creates an endpoint

        Args:
            settings (dict): see below key value pairs
                'response_type' (tuple/None): response type
                'auth' (list): a list of auth type keys
                'endpoint_path' (str): the endpoint path
                'operation_id' (str): endpoint string identifier
                'http_method' (str): POST/PUT/PATCH/GET etc
                'servers' (list): list of str servers that this endpoint is at
            params_map (dict): see below key value pairs
                'all' (list): list of str endpoint parameter names
                'required' (list): list of required parameter names
                'nullable' (list): list of nullable parameter names
                'enum' (list): list of parameters with enum values
                'validation' (list): list of parameters with validations
            root_map
                'validations' (dict): the dict mapping endpoint parameter tuple
                    paths to their validation dictionaries
                'allowed_values' (dict): the dict mapping endpoint parameter
                    tuple paths to their allowed_values (enum) dictionaries
                'openapi_types' (dict): param_name to openapi type
                'attribute_map' (dict): param_name to camelCase name
                'location_map' (dict): param_name to  'body', 'file', 'form',
                    'header', 'path', 'query'
                collection_format_map (dict): param_name to `csv` etc.
            headers_map (dict): see below key value pairs
                'accept' (list): list of Accept header strings
                'content_type' (list): list of Content-Type header strings
            api_client (ApiClient) api client instance
            callable (function): the function which is invoked when the
                Endpoint is called
        """
        self.settings = settings
        self.params_map = params_map
        self.params_map['all'].extend([
            'async_req',
            '_host_index',
            '_preload_content',
            '_request_timeout',
            '_return_http_data_only',
            '_check_input_type',
            '_check_return_type'
        ])
        self.params_map['nullable'].extend(['_request_timeout'])
        self.validations = root_map['validations']
        self.allowed_values = root_map['allowed_values']
        self.openapi_types = root_map['openapi_types']
        extra_types = {
            'async_req': (bool,),
            '_host_index': (int,),
            '_preload_content': (bool,),
            '_request_timeout': (none_type, int, (int,), [int]),
            '_return_http_data_only': (bool,),
            '_check_input_type': (bool,),
            '_check_return_type': (bool,)
        }
        self.openapi_types.update(extra_types)
        self.attribute_map = root_map['attribute_map']
        self.location_map = root_map['location_map']
        self.collection_format_map = root_map['collection_format_map']
        self.headers_map = headers_map
        self.api_client = api_client
        self.callable = callable

    def __validate_inputs(self, kwargs):
        for param in self.params_map['enum']:
            if param in kwargs:
                check_allowed_values(
                    self.allowed_values,
                    (param,),
                    kwargs[param]
                )

        for param in self.params_map['validation']:
            if param in kwargs:
                check_validations(
                    self.validations,
                    (param,),
                    kwargs[param]
                )

        if kwargs['_check_input_type'] is False:
            return

        for key, value in six.iteritems(kwargs):
            fixed_val = validate_and_convert_types(
                value,
                self.openapi_types[key],
                [key],
                False,
                kwargs['_check_input_type'],
                configuration=self.api_client.configuration
            )
            kwargs[key] = fixed_val

    def __gather_params(self, kwargs):
        params = {
            'body': None,
            'collection_format': {},
            'file': {},
            'form': [],
            'header': {},
            'path': {},
            'query': []
        }

        for param_name, param_value in six.iteritems(kwargs):
            param_location = self.location_map.get(param_name)
            if param_location is None:
                continue
            if param_location:
                if param_location == 'body':
                    params['body'] = param_value
                    continue
                base_name = self.attribute_map[param_name]
                if (param_location == 'form' and
                        self.openapi_types[param_name] == (file_type,)):
                    params['file'][param_name] = [param_value]
                elif (param_location == 'form' and
                        self.openapi_types[param_name] == ([file_type],)):
                    # param_value is already a list
                    params['file'][param_name] = param_value
                elif param_location in {'form', 'query'}:
                    param_value_full = (base_name, param_value)
                    params[param_location].append(param_value_full)
                if param_location not in {'form', 'query'}:
                    params[param_location][base_name] = param_value
                collection_format = self.collection_format_map.get(param_name)
                if collection_format:
                    params['collection_format'][base_name] = collection_format

        return params

    def __call__(self, *args, **kwargs):
        """ This method is invoked when endpoints are called
        Example:
        pet_api = PetApi()
        pet_api.add_pet  # this is an instance of the class Endpoint
        pet_api.add_pet()  # this invokes pet_api.add_pet.__call__()
        which then invokes the callable functions stored in that endpoint at
        pet_api.add_pet.callable or self.callable in this class
        """
        return self.callable(self, *args, **kwargs)

    def call_with_http_info(self, **kwargs):

        try:
            _host = self.settings['servers'][kwargs['_host_index']]
        except IndexError:
            if self.settings['servers']:
                raise ApiValueError(
                    "Invalid host index. Must be 0 <= index < %s" %
                    len(self.settings['servers'])
                )
            _host = None

        for key, value in six.iteritems(kwargs):
            if key not in self.params_map['all']:
                raise ApiTypeError(
                    "Got an unexpected parameter '%s'"
                    " to method `%s`" %
                    (key, self.settings['operation_id'])
                )
            # only throw this nullable ApiValueError if _check_input_type
            # is False, if _check_input_type==True we catch this case
            # in self.__validate_inputs
            if (key not in self.params_map['nullable'] and value is None
                    and kwargs['_check_input_type'] is False):
                raise ApiValueError(
                    "Value may not be None for non-nullable parameter `%s`"
                    " when calling `%s`" %
                    (key, self.settings['operation_id'])
                )

        for key in self.params_map['required']:
            if key not in kwargs.keys():
                raise ApiValueError(
                    "Missing the required parameter `%s` when calling "
                    "`%s`" % (key, self.settings['operation_id'])
                )

        self.__validate_inputs(kwargs)

        params = self.__gather_params(kwargs)

        accept_headers_list = self.headers_map['accept']
        if accept_headers_list:
            params['header']['Accept'] = self.api_client.select_header_accept(
                accept_headers_list)

        content_type_headers_list = self.headers_map['content_type']
        if content_type_headers_list:
            header_list = self.api_client.select_header_content_type(
                content_type_headers_list)
            params['header']['Content-Type'] = header_list

        return self.api_client.call_api(
            self.settings['endpoint_path'], self.settings['http_method'],
            params['path'],
            params['query'],
            params['header'],
            body=params['body'],
            post_params=params['form'],
            files=params['file'],
            response_type=self.settings['response_type'],
            auth_settings=self.settings['auth'],
            async_req=kwargs['async_req'],
            _check_type=kwargs['_check_return_type'],
            _return_http_data_only=kwargs['_return_http_data_only'],
            _preload_content=kwargs['_preload_content'],
            _request_timeout=kwargs['_request_timeout'],
            _host=_host,
            collection_formats=params['collection_format'])
