# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.realms_admin_api import RealmsAdminApi  # noqa: E501
from openapi_client.rest import ApiException


class TestRealmsAdminApi(unittest.TestCase):
    """RealmsAdminApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.realms_admin_api.RealmsAdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_get(self):
        """Test case for admin_realms_get

        Get accessible realms Returns a list of accessible realms. The list is filtered based on what realms the caller is allowed to view.  # noqa: E501
        """
        pass

    def test_admin_realms_post(self):
        """Test case for admin_realms_post

        Import a realm. Imports a realm from a full representation of that realm.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_admin_events_delete(self):
        """Test case for admin_realms_realm_admin_events_delete

        Delete all admin events  # noqa: E501
        """
        pass

    def test_admin_realms_realm_admin_events_get(self):
        """Test case for admin_realms_realm_admin_events_get

        Get admin events Returns all admin events, or filters events based on URL query parameters listed here  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_description_converter_post(self):
        """Test case for admin_realms_realm_client_description_converter_post

        Base path for importing clients under this realm.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_policies_policies_get(self):
        """Test case for admin_realms_realm_client_policies_policies_get

        /admin/realms/{realm}/client-policies/policies  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_policies_policies_put(self):
        """Test case for admin_realms_realm_client_policies_policies_put

        /admin/realms/{realm}/client-policies/policies  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_policies_profiles_get(self):
        """Test case for admin_realms_realm_client_policies_profiles_get

        /admin/realms/{realm}/client-policies/profiles  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_policies_profiles_put(self):
        """Test case for admin_realms_realm_client_policies_profiles_put

        /admin/realms/{realm}/client-policies/profiles  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_session_stats_get(self):
        """Test case for admin_realms_realm_client_session_stats_get

        Get client session stats Returns a JSON map.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_types_get(self):
        """Test case for admin_realms_realm_client_types_get

        List all client types available in the current realm  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_types_put(self):
        """Test case for admin_realms_realm_client_types_put

        Update a client type  # noqa: E501
        """
        pass

    def test_admin_realms_realm_credential_registrators_get(self):
        """Test case for admin_realms_realm_credential_registrators_get

        /admin/realms/{realm}/credential-registrators  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_default_client_scopes_client_scope_id_delete(self):
        """Test case for admin_realms_realm_default_default_client_scopes_client_scope_id_delete

        /admin/realms/{realm}/default-default-client-scopes/{clientScopeId}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_default_client_scopes_client_scope_id_put(self):
        """Test case for admin_realms_realm_default_default_client_scopes_client_scope_id_put

        /admin/realms/{realm}/default-default-client-scopes/{clientScopeId}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_default_client_scopes_get(self):
        """Test case for admin_realms_realm_default_default_client_scopes_get

        Get realm default client scopes.  Only name and ids are returned.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_groups_get(self):
        """Test case for admin_realms_realm_default_groups_get

        Get group hierarchy.  Only name and ids are returned.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_groups_group_id_delete(self):
        """Test case for admin_realms_realm_default_groups_group_id_delete

        /admin/realms/{realm}/default-groups/{groupId}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_groups_group_id_put(self):
        """Test case for admin_realms_realm_default_groups_group_id_put

        /admin/realms/{realm}/default-groups/{groupId}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_optional_client_scopes_client_scope_id_delete(self):
        """Test case for admin_realms_realm_default_optional_client_scopes_client_scope_id_delete

        /admin/realms/{realm}/default-optional-client-scopes/{clientScopeId}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_optional_client_scopes_client_scope_id_put(self):
        """Test case for admin_realms_realm_default_optional_client_scopes_client_scope_id_put

        /admin/realms/{realm}/default-optional-client-scopes/{clientScopeId}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_default_optional_client_scopes_get(self):
        """Test case for admin_realms_realm_default_optional_client_scopes_get

        Get realm optional client scopes.  Only name and ids are returned.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_delete(self):
        """Test case for admin_realms_realm_delete

        Delete the realm  # noqa: E501
        """
        pass

    def test_admin_realms_realm_events_config_get(self):
        """Test case for admin_realms_realm_events_config_get

        Get the events provider configuration Returns JSON object with events provider configuration  # noqa: E501
        """
        pass

    def test_admin_realms_realm_events_config_put(self):
        """Test case for admin_realms_realm_events_config_put

        /admin/realms/{realm}/events/config  # noqa: E501
        """
        pass

    def test_admin_realms_realm_events_delete(self):
        """Test case for admin_realms_realm_events_delete

        Delete all events  # noqa: E501
        """
        pass

    def test_admin_realms_realm_events_get(self):
        """Test case for admin_realms_realm_events_get

        Get events Returns all events, or filters them based on URL query parameters listed here  # noqa: E501
        """
        pass

    def test_admin_realms_realm_get(self):
        """Test case for admin_realms_realm_get

        Get the top-level representation of the realm It will not include nested information like User and Client representations.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_group_by_path_path_get(self):
        """Test case for admin_realms_realm_group_by_path_path_get

        /admin/realms/{realm}/group-by-path/{path}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_localization_get(self):
        """Test case for admin_realms_realm_localization_get

        /admin/realms/{realm}/localization  # noqa: E501
        """
        pass

    def test_admin_realms_realm_localization_locale_delete(self):
        """Test case for admin_realms_realm_localization_locale_delete

        /admin/realms/{realm}/localization/{locale}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_localization_locale_get(self):
        """Test case for admin_realms_realm_localization_locale_get

        /admin/realms/{realm}/localization/{locale}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_localization_locale_key_delete(self):
        """Test case for admin_realms_realm_localization_locale_key_delete

        /admin/realms/{realm}/localization/{locale}/{key}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_localization_locale_key_get(self):
        """Test case for admin_realms_realm_localization_locale_key_get

        /admin/realms/{realm}/localization/{locale}/{key}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_localization_locale_key_put(self):
        """Test case for admin_realms_realm_localization_locale_key_put

        /admin/realms/{realm}/localization/{locale}/{key}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_localization_locale_post(self):
        """Test case for admin_realms_realm_localization_locale_post

        Import localization from uploaded JSON file  # noqa: E501
        """
        pass

    def test_admin_realms_realm_logout_all_post(self):
        """Test case for admin_realms_realm_logout_all_post

        Removes all user sessions.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_partial_export_post(self):
        """Test case for admin_realms_realm_partial_export_post

        Partial export of existing realm into a JSON file.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_partial_import_post(self):
        """Test case for admin_realms_realm_partial_import_post

        Partial import from a JSON file to an existing realm.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_push_revocation_post(self):
        """Test case for admin_realms_realm_push_revocation_post

        Push the realm's revocation policy to any client that has an admin url associated with it.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_put(self):
        """Test case for admin_realms_realm_put

        Update the top-level information of the realm Any user, roles or client information in the representation will be ignored.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_sessions_session_delete(self):
        """Test case for admin_realms_realm_sessions_session_delete

        Remove a specific user session.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_test_smtp_connection_post(self):
        """Test case for admin_realms_realm_test_smtp_connection_post

        Test SMTP connection with current logged in user  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_management_permissions_get(self):
        """Test case for admin_realms_realm_users_management_permissions_get

        /admin/realms/{realm}/users-management-permissions  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_management_permissions_put(self):
        """Test case for admin_realms_realm_users_management_permissions_put

        /admin/realms/{realm}/users-management-permissions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
