# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client
from keycloak_admin_client.api.keycloak_admin_api import KeycloakAdminApi  # noqa: E501
from keycloak_admin_client.rest import ApiException


class TestKeycloakAdminApi(unittest.TestCase):
    """KeycloakAdminApi unit test stubs"""

    def setUp(self):
        self.api = keycloak_admin_client.api.keycloak_admin_api.KeycloakAdminApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_import_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_import_post

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/import  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_permission_evaluate_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_permission_evaluate_post

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission/evaluate  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_permission_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_permission_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_permission_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_permission_post

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_permission_providers_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_permission_providers_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission/providers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_permission_search_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_permission_search_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/permission/search  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_policy_evaluate_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_policy_evaluate_post

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy/evaluate  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_policy_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_policy_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_policy_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_policy_post

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_policy_providers_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_policy_providers_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy/providers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_policy_search_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_policy_search_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/policy/search  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_put(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_put

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_post

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_attributes_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_attributes_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}/attributes  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_delete(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_delete

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_permissions_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_permissions_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}/permissions  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_put(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_put

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_scopes_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_resource_id_scopes_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/{resource-id}/scopes  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_resource_search_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_resource_search_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/resource/search  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_post

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_delete(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_delete

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_permissions_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_permissions_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}/permissions  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_put(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_put

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_resources_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_scope_id_resources_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/{scope-id}/resources  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_scope_search_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_scope_search_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/scope/search  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_authz_resource_server_settings_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_authz_resource_server_settings_get

        /admin/realms/{realm}/clients/{client-uuid}/authz/resource-server/settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
