# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client
from keycloak_admin_client.api.keycloak_admin_role_mapper_api import KeycloakAdminRoleMapperApi  # noqa: E501
from keycloak_admin_client.rest import ApiException


class TestKeycloakAdminRoleMapperApi(unittest.TestCase):
    """KeycloakAdminRoleMapperApi unit test stubs"""

    def setUp(self):
        self.api = keycloak_admin_client.api.keycloak_admin_role_mapper_api.KeycloakAdminRoleMapperApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_groups_group_id_role_mappings_get(self):
        """Test case for admin_realms_realm_groups_group_id_role_mappings_get

        Get role mappings  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_role_mappings_realm_available_get(self):
        """Test case for admin_realms_realm_groups_group_id_role_mappings_realm_available_get

        Get realm-level roles that can be mapped  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_role_mappings_realm_composite_get(self):
        """Test case for admin_realms_realm_groups_group_id_role_mappings_realm_composite_get

        Get effective realm-level role mappings This will recurse all composite roles to get the result.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_role_mappings_realm_delete(self):
        """Test case for admin_realms_realm_groups_group_id_role_mappings_realm_delete

        Delete realm-level role mappings  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_role_mappings_realm_get(self):
        """Test case for admin_realms_realm_groups_group_id_role_mappings_realm_get

        Get realm-level role mappings  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_role_mappings_realm_post(self):
        """Test case for admin_realms_realm_groups_group_id_role_mappings_realm_post

        Add realm-level role mappings to the user  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_user_id_role_mappings_get(self):
        """Test case for admin_realms_realm_users_user_id_role_mappings_get

        Get role mappings  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_user_id_role_mappings_realm_available_get(self):
        """Test case for admin_realms_realm_users_user_id_role_mappings_realm_available_get

        Get realm-level roles that can be mapped  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_user_id_role_mappings_realm_composite_get(self):
        """Test case for admin_realms_realm_users_user_id_role_mappings_realm_composite_get

        Get effective realm-level role mappings This will recurse all composite roles to get the result.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_user_id_role_mappings_realm_delete(self):
        """Test case for admin_realms_realm_users_user_id_role_mappings_realm_delete

        Delete realm-level role mappings  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_user_id_role_mappings_realm_get(self):
        """Test case for admin_realms_realm_users_user_id_role_mappings_realm_get

        Get realm-level role mappings  # noqa: E501
        """
        pass

    def test_admin_realms_realm_users_user_id_role_mappings_realm_post(self):
        """Test case for admin_realms_realm_users_user_id_role_mappings_realm_post

        Add realm-level role mappings to the user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
