# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client
from keycloak_admin_client.api.key_api import KeyApi  # noqa: E501
from keycloak_admin_client.rest import ApiException


class TestKeyApi(unittest.TestCase):
    """KeyApi unit test stubs"""

    def setUp(self):
        self.api = keycloak_admin_client.api.key_api.KeyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_keys_get(self):
        """Test case for admin_realms_realm_keys_get

        /admin/realms/{realm}/keys  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
