# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.client_initial_access_api import ClientInitialAccessApi  # noqa: E501
from openapi_client.rest import ApiException


class TestClientInitialAccessApi(unittest.TestCase):
    """ClientInitialAccessApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.client_initial_access_api.ClientInitialAccessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_clients_initial_access_get(self):
        """Test case for admin_realms_realm_clients_initial_access_get

        /admin/realms/{realm}/clients-initial-access  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_initial_access_id_delete(self):
        """Test case for admin_realms_realm_clients_initial_access_id_delete

        /admin/realms/{realm}/clients-initial-access/{id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_initial_access_post(self):
        """Test case for admin_realms_realm_clients_initial_access_post

        Create a new initial access token.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
