# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.neer_users_api import NeerUsersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNeerUsersApi(unittest.TestCase):
    """NeerUsersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.neer_users_api.NeerUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_users(self):
        """Test case for count_users

        Count users  # noqa: E501
        """
        pass

    def test_create_user(self):
        """Test case for create_user

        Create a new user  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a user  # noqa: E501
        """
        pass

    def test_export_users(self):
        """Test case for export_users

        Export users  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get user details  # noqa: E501
        """
        pass

    def test_import_users(self):
        """Test case for import_users

        Import users  # noqa: E501
        """
        pass

    def test_list_users(self):
        """Test case for list_users

        List users  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update a user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
