# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.keycloak_admin_groups_api import KeycloakAdminGroupsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestKeycloakAdminGroupsApi(unittest.TestCase):
    """KeycloakAdminGroupsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.keycloak_admin_groups_api.KeycloakAdminGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_groups_count_get(self):
        """Test case for admin_realms_realm_groups_count_get

        Returns the groups counts.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_get(self):
        """Test case for admin_realms_realm_groups_get

        Get group hierarchy.  Only name and ids are returned.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_children_get(self):
        """Test case for admin_realms_realm_groups_group_id_children_get

        Return a paginated list of subgroups that have a parent group corresponding to the group on the URL  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_children_post(self):
        """Test case for admin_realms_realm_groups_group_id_children_post

        Set or create child.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_delete(self):
        """Test case for admin_realms_realm_groups_group_id_delete

        /admin/realms/{realm}/groups/{group-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_get(self):
        """Test case for admin_realms_realm_groups_group_id_get

        /admin/realms/{realm}/groups/{group-id}  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_management_permissions_get(self):
        """Test case for admin_realms_realm_groups_group_id_management_permissions_get

        Return object stating whether client Authorization permissions have been initialized or not and a reference  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_management_permissions_put(self):
        """Test case for admin_realms_realm_groups_group_id_management_permissions_put

        Return object stating whether client Authorization permissions have been initialized or not and a reference  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_members_get(self):
        """Test case for admin_realms_realm_groups_group_id_members_get

        Get users Returns a stream of users, filtered according to query parameters  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_group_id_put(self):
        """Test case for admin_realms_realm_groups_group_id_put

        Update group, ignores subgroups.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_groups_post(self):
        """Test case for admin_realms_realm_groups_post

        create or add a top level realm groupSet or create child.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
