# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.client_scopes_api import ClientScopesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestClientScopesApi(unittest.TestCase):
    """ClientScopesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.client_scopes_api.ClientScopesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_delete(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_delete

        Delete the client scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_get(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_get

        Get representation of the client scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_put(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_put

        Update the client scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_get(self):
        """Test case for admin_realms_realm_client_scopes_get

        Get client scopes belonging to the realm Returns a list of client scopes belonging to the realm  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_post(self):
        """Test case for admin_realms_realm_client_scopes_post

        Create a new client scope Client Scope’s name must be unique!  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_delete(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_delete

        Delete the client scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_get(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_get

        Get representation of the client scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_put(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_put

        Update the client scope  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_get(self):
        """Test case for admin_realms_realm_client_templates_get

        Get client scopes belonging to the realm Returns a list of client scopes belonging to the realm  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_post(self):
        """Test case for admin_realms_realm_client_templates_post

        Create a new client scope Client Scope’s name must be unique!  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
