# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.keycloak_admin_attack_detection_api import KeycloakAdminAttackDetectionApi  # noqa: E501
from openapi_client.rest import ApiException


class TestKeycloakAdminAttackDetectionApi(unittest.TestCase):
    """KeycloakAdminAttackDetectionApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.keycloak_admin_attack_detection_api.KeycloakAdminAttackDetectionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_attack_detection_brute_force_users_delete(self):
        """Test case for admin_realms_realm_attack_detection_brute_force_users_delete

        Clear any user login failures for all users This can release temporary disabled users  # noqa: E501
        """
        pass

    def test_admin_realms_realm_attack_detection_brute_force_users_user_id_delete(self):
        """Test case for admin_realms_realm_attack_detection_brute_force_users_user_id_delete

        Clear any user login failures for the user This can release temporary disabled user  # noqa: E501
        """
        pass

    def test_admin_realms_realm_attack_detection_brute_force_users_user_id_get(self):
        """Test case for admin_realms_realm_attack_detection_brute_force_users_user_id_get

        Get status of a username in brute force detection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
