# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client
from keycloak_admin_client.api.neer_readings_api import NeerReadingsApi  # noqa: E501
from keycloak_admin_client.rest import ApiException


class TestNeerReadingsApi(unittest.TestCase):
    """NeerReadingsApi unit test stubs"""

    def setUp(self):
        self.api = keycloak_admin_client.api.neer_readings_api.NeerReadingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_reading(self):
        """Test case for create_reading

        Create a reading  # noqa: E501
        """
        pass

    def test_delete_reading(self):
        """Test case for delete_reading

        Delete a meter reading  # noqa: E501
        """
        pass

    def test_export_readings(self):
        """Test case for export_readings

        Export meter readings  # noqa: E501
        """
        pass

    def test_get_reading(self):
        """Test case for get_reading

        Get a meter reading  # noqa: E501
        """
        pass

    def test_import_readings(self):
        """Test case for import_readings

        Import meter readings  # noqa: E501
        """
        pass

    def test_list_readings(self):
        """Test case for list_readings

        List meter readings  # noqa: E501
        """
        pass

    def test_update_reading(self):
        """Test case for update_reading

        Update a meter reading  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
