# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.neer_meters_api import NeerMetersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNeerMetersApi(unittest.TestCase):
    """NeerMetersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.neer_meters_api.NeerMetersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_meter(self):
        """Test case for create_meter

        Create a new meter  # noqa: E501
        """
        pass

    def test_delete_meter(self):
        """Test case for delete_meter

        Delete a meter  # noqa: E501
        """
        pass

    def test_export_meters(self):
        """Test case for export_meters

        Export meters  # noqa: E501
        """
        pass

    def test_get_meter(self):
        """Test case for get_meter

        Get a meter  # noqa: E501
        """
        pass

    def test_import_meters(self):
        """Test case for import_meters

        Import meters  # noqa: E501
        """
        pass

    def test_list_meters(self):
        """Test case for list_meters

        List meters  # noqa: E501
        """
        pass

    def test_update_meter(self):
        """Test case for update_meter

        Update a meter  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
