# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.tenant_vendors_api import TenantVendorsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTenantVendorsApi(unittest.TestCase):
    """TenantVendorsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tenant_vendors_api.TenantVendorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_vendor_to_tenant(self):
        """Test case for add_vendor_to_tenant

        Add vendor to tenant  # noqa: E501
        """
        pass

    def test_delete_vendor_from_tenant(self):
        """Test case for delete_vendor_from_tenant

        Delete vendor from tenant  # noqa: E501
        """
        pass

    def test_get_vendor_count_from_tenant(self):
        """Test case for get_vendor_count_from_tenant

        Get vendor count from tenant  # noqa: E501
        """
        pass

    def test_get_vendor_from_tenant(self):
        """Test case for get_vendor_from_tenant

        Get vendor from tenant  # noqa: E501
        """
        pass

    def test_list_vendors_from_tenant(self):
        """Test case for list_vendors_from_tenant

        List vendors from tenant  # noqa: E501
        """
        pass

    def test_update_vendor_from_tenant(self):
        """Test case for update_vendor_from_tenant

        Update vendor from tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
