# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client
from keycloak_admin_client.api.units_api import UnitsApi  # noqa: E501
from keycloak_admin_client.rest import ApiException


class TestUnitsApi(unittest.TestCase):
    """UnitsApi unit test stubs"""

    def setUp(self):
        self.api = keycloak_admin_client.api.units_api.UnitsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_units(self):
        """Test case for count_units

        Count units  # noqa: E501
        """
        pass

    def test_create_unit(self):
        """Test case for create_unit

        Create a new unit  # noqa: E501
        """
        pass

    def test_delete_unit(self):
        """Test case for delete_unit

        Delete a unit  # noqa: E501
        """
        pass

    def test_export_units(self):
        """Test case for export_units

        Export units  # noqa: E501
        """
        pass

    def test_get_unit(self):
        """Test case for get_unit

        Get a unit  # noqa: E501
        """
        pass

    def test_import_units(self):
        """Test case for import_units

        Import units  # noqa: E501
        """
        pass

    def test_list_units(self):
        """Test case for list_units

        List units  # noqa: E501
        """
        pass

    def test_update_unit(self):
        """Test case for update_unit

        Update a unit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
