# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client
from keycloak_admin_client.api.keycloak_admin_protocol_mappers_api import KeycloakAdminProtocolMappersApi  # noqa: E501
from keycloak_admin_client.rest import ApiException


class TestKeycloakAdminProtocolMappersApi(unittest.TestCase):
    """KeycloakAdminProtocolMappersApi unit test stubs"""

    def setUp(self):
        self.api = keycloak_admin_client.api.keycloak_admin_protocol_mappers_api.KeycloakAdminProtocolMappersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_add_models_post(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_add_models_post

        Create multiple mappers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_get(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_get

        Get mappers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_id_delete(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_id_delete

        Delete the mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_id_get(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_id_get

        Get mapper by id  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_id_put(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_id_put

        Update the mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_post(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_models_post

        Create a mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_protocol_protocol_get(self):
        """Test case for admin_realms_realm_client_scopes_client_scope_id_protocol_mappers_protocol_protocol_get

        Get mappers by name for a specific protocol  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_protocol_mappers_add_models_post(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_protocol_mappers_add_models_post

        Create multiple mappers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_get(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_get

        Get mappers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_id_delete(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_id_delete

        Delete the mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_id_get(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_id_get

        Get mapper by id  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_id_put(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_id_put

        Update the mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_post(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_protocol_mappers_models_post

        Create a mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_client_templates_client_scope_id_protocol_mappers_protocol_protocol_get(self):
        """Test case for admin_realms_realm_client_templates_client_scope_id_protocol_mappers_protocol_protocol_get

        Get mappers by name for a specific protocol  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_protocol_mappers_add_models_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_protocol_mappers_add_models_post

        Create multiple mappers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_protocol_mappers_models_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_protocol_mappers_models_get

        Get mappers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_protocol_mappers_models_id_delete(self):
        """Test case for admin_realms_realm_clients_client_uuid_protocol_mappers_models_id_delete

        Delete the mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_protocol_mappers_models_id_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_protocol_mappers_models_id_get

        Get mapper by id  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_protocol_mappers_models_id_put(self):
        """Test case for admin_realms_realm_clients_client_uuid_protocol_mappers_models_id_put

        Update the mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_protocol_mappers_models_post(self):
        """Test case for admin_realms_realm_clients_client_uuid_protocol_mappers_models_post

        Create a mapper  # noqa: E501
        """
        pass

    def test_admin_realms_realm_clients_client_uuid_protocol_mappers_protocol_protocol_get(self):
        """Test case for admin_realms_realm_clients_client_uuid_protocol_mappers_protocol_protocol_get

        Get mappers by name for a specific protocol  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
