# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.neer_vendors_api import NeerVendorsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNeerVendorsApi(unittest.TestCase):
    """NeerVendorsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.neer_vendors_api.NeerVendorsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_count_vendors(self):
        """Test case for count_vendors

        Count vendors  # noqa: E501
        """
        pass

    def test_create_vendor(self):
        """Test case for create_vendor

        Create a new vendor  # noqa: E501
        """
        pass

    def test_delete_vendor(self):
        """Test case for delete_vendor

        Delete a vendor  # noqa: E501
        """
        pass

    def test_export_vendors(self):
        """Test case for export_vendors

        Export vendors  # noqa: E501
        """
        pass

    def test_get_vendor(self):
        """Test case for get_vendor

        Get a vendor  # noqa: E501
        """
        pass

    def test_import_vendors(self):
        """Test case for import_vendors

        Import vendors  # noqa: E501
        """
        pass

    def test_list_vendors(self):
        """Test case for list_vendors

        List vendors  # noqa: E501
        """
        pass

    def test_update_vendor(self):
        """Test case for update_vendor

        Update a vendor  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
