# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.neer_tenant_users_api import NeerTenantUsersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestNeerTenantUsersApi(unittest.TestCase):
    """NeerTenantUsersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.neer_tenant_users_api.NeerTenantUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_to_tenant(self):
        """Test case for add_user_to_tenant

        Add user to tenant  # noqa: E501
        """
        pass

    def test_delete_user_from_tenant(self):
        """Test case for delete_user_from_tenant

        Delete user from tenant  # noqa: E501
        """
        pass

    def test_get_user_count_from_tenant(self):
        """Test case for get_user_count_from_tenant

        Get user count from tenant  # noqa: E501
        """
        pass

    def test_get_user_from_tenant(self):
        """Test case for get_user_from_tenant

        Get user from tenant  # noqa: E501
        """
        pass

    def test_list_users_from_tenant(self):
        """Test case for list_users_from_tenant

        List users from tenant  # noqa: E501
        """
        pass

    def test_update_user_from_tenant(self):
        """Test case for update_user_from_tenant

        Update user from tenant  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
