# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client


class TestUserListResSchema(unittest.TestCase):
    """UserListResSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserListResSchema(self):
        """Test UserListResSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.UserListResSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
