# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.keycloak_admin_roles__by_id_api import KeycloakAdminRolesByIDApi  # noqa: E501
from openapi_client.rest import ApiException


class TestKeycloakAdminRolesByIDApi(unittest.TestCase):
    """KeycloakAdminRolesByIDApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.keycloak_admin_roles__by_id_api.KeycloakAdminRolesByIDApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_roles_by_id_role_id_composites_clients_client_uuid_get(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_composites_clients_client_uuid_get

        Get client-level roles for the client that are in the role's composite  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_composites_delete(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_composites_delete

        Remove a set of roles from the role's composite  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_composites_get(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_composites_get

        Get role's children Returns a set of role's children provided the role is a composite.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_composites_post(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_composites_post

        Make the role a composite role by associating some child roles  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_composites_realm_get(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_composites_realm_get

        Get realm-level roles that are in the role's composite  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_delete(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_delete

        Delete the role  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_get(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_get

        Get a specific role's representation  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_management_permissions_get(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_management_permissions_get

        Return object stating whether role Authorization permissions have been initialized or not and a reference  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_management_permissions_put(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_management_permissions_put

        Return object stating whether role Authorization permissions have been initialized or not and a reference  # noqa: E501
        """
        pass

    def test_admin_realms_realm_roles_by_id_role_id_put(self):
        """Test case for admin_realms_realm_roles_by_id_role_id_put

        Update the role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
