# coding: utf-8

"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import keycloak_admin_client
from keycloak_admin_client.api.identity_providers_api import IdentityProvidersApi  # noqa: E501
from keycloak_admin_client.rest import ApiException


class TestIdentityProvidersApi(unittest.TestCase):
    """IdentityProvidersApi unit test stubs"""

    def setUp(self):
        self.api = keycloak_admin_client.api.identity_providers_api.IdentityProvidersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_realms_realm_identity_provider_import_config_post(self):
        """Test case for admin_realms_realm_identity_provider_import_config_post

        Import identity provider from JSON body  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_delete(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_delete

        Delete the identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_export_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_export_get

        Export public broker configuration for identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_get

        Get the identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_management_permissions_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_management_permissions_get

        Return object stating whether client Authorization permissions have been initialized or not and a reference  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_management_permissions_put(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_management_permissions_put

        Return object stating whether client Authorization permissions have been initialized or not and a reference  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_mapper_types_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_mapper_types_get

        Get mapper types for identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_mappers_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_mappers_get

        Get mappers for identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_mappers_id_delete(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_mappers_id_delete

        Delete a mapper for the identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_mappers_id_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_mappers_id_get

        Get mapper by id for the identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_mappers_id_put(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_mappers_id_put

        Update a mapper for the identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_mappers_post(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_mappers_post

        Add a mapper to identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_put(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_put

        Update the identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_alias_reload_keys_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_alias_reload_keys_get

        Reaload keys for the identity provider if the provider supports it, \"true\" is returned if reload was performed, \"false\" if not.  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_get(self):
        """Test case for admin_realms_realm_identity_provider_instances_get

        List identity providers  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_instances_post(self):
        """Test case for admin_realms_realm_identity_provider_instances_post

        Create a new identity provider  # noqa: E501
        """
        pass

    def test_admin_realms_realm_identity_provider_providers_provider_id_get(self):
        """Test case for admin_realms_realm_identity_provider_providers_provider_id_get

        Get the identity provider factory for that provider id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
