# coding: utf-8

# flake8: noqa
"""
    My Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


# we can not import model classes here because that would create a circular
# reference which would not work in python2
